// <auto-generated />
namespace CoursesReg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlzWork453 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlzWork453));
        
        string IMigrationMetadata.Id
        {
            get { return "201904160928565_PlzWork453"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
