// <auto-generated />
namespace CoursesReg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlzWork4221 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlzWork4221));
        
        string IMigrationMetadata.Id
        {
            get { return "201904161000344_PlzWork4221"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
